In [14]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt


In [34]:
# 加载数据集
train_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True, 
    transform=ToTensor(),
)
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True, 
    transform=ToTensor(),
)
d = test_data[-1][0]
print(d.shape)

torch.Size([1, 28, 28])


In [35]:
BATCH_SIZE = 64
train_dataloader = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=BATCH_SIZE, shuffle=False)
for x,y in test_dataloader:
    print(x.shape)
    print(y.shape, type(y))


torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64]) <cl

In [41]:
# 构建模型
device = "cuda" if torch.cuda.is_available() else "cpu"
class NeuraNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.liner_relu = nn.Sequential(
            nn.Linear(28*28,64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )
    
    def forward(self, x):
        x = self.flatten(x)
        return self.liner_relu(x)
model = NeuraNetwork()
print(model)

NeuraNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (liner_relu): Sequential(
    (0): Linear(in_features=784, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=10, bias=True)
  )
)


In [42]:
input_image = torch.rand(3,28,28)
print(input_image)

tensor([[[0.2078, 0.0913, 0.5995,  ..., 0.4428, 0.9745, 0.7647],
         [0.2830, 0.3782, 0.6068,  ..., 0.1284, 0.8411, 0.8196],
         [0.6744, 0.6557, 0.2281,  ..., 0.1347, 0.2724, 0.3676],
         ...,
         [0.2519, 0.5605, 0.1000,  ..., 0.0151, 0.3900, 0.6485],
         [0.6339, 0.6893, 0.5513,  ..., 0.3978, 0.8770, 0.0943],
         [0.1990, 0.1628, 0.7573,  ..., 0.2166, 0.6994, 0.5917]],

        [[0.7288, 0.3792, 0.6352,  ..., 0.9893, 0.0727, 0.6407],
         [0.2899, 0.4763, 0.8086,  ..., 0.4469, 0.3278, 0.3809],
         [0.8266, 0.9589, 0.6426,  ..., 0.4632, 0.6657, 0.5661],
         ...,
         [0.3408, 0.4203, 0.6949,  ..., 0.3626, 0.2016, 0.9471],
         [0.0656, 0.3453, 0.1031,  ..., 0.5046, 0.2501, 0.9745],
         [0.2134, 0.5840, 0.1866,  ..., 0.8500, 0.6338, 0.1065]],

        [[0.3543, 0.0267, 0.2666,  ..., 0.6018, 0.3749, 0.4762],
         [0.9366, 0.3948, 0.0992,  ..., 0.9929, 0.1546, 0.2609],
         [0.6609, 0.4606, 0.0920,  ..., 0.3186, 0.7708, 0.

In [49]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [50]:
layer1 = nn.Linear(in_features=28*28,out_features=10)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 10])


In [51]:

hidden1 = nn.ReLU()(hidden1)
print(hidden1)

tensor([[0.4961, 0.5803, 0.0000, 0.1551, 0.2369, 0.0000, 0.1769, 0.0000, 0.7113,
         0.0000],
        [0.4729, 0.5906, 0.1995, 0.0000, 0.3080, 0.0000, 0.6176, 0.0387, 0.3942,
         0.0000],
        [0.0713, 0.5079, 0.4316, 0.3134, 0.1539, 0.0392, 0.7300, 0.0000, 0.5649,
         0.0000]], grad_fn=<ReluBackward0>)


In [54]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(10,10)
)
input_image = torch.rand(3,28,28)
loss = seq_modules(input_image)
print(loss)

tensor([[ 0.0391, -0.3672, -0.2971, -0.2323,  0.1300, -0.4055, -0.0580, -0.1508,
          0.1274,  0.3878],
        [ 0.0785, -0.3148, -0.2659, -0.2784,  0.1189, -0.2383, -0.2246, -0.1970,
          0.1156,  0.3096],
        [ 0.1633, -0.3089, -0.2964, -0.1048, -0.0763, -0.2654, -0.2217, -0.3618,
          0.1011,  0.5405]], grad_fn=<AddmmBackward0>)


In [55]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(loss)