In [1]:
import torch 
import torch.nn as nn
a = nn.Embedding(10, 3)
print(a.weight)
print(a.weight.shape)

Parameter containing:
tensor([[-0.7618, -0.2621, -0.8623],
        [ 0.4043, -1.4023,  1.1573],
        [-0.2983,  0.3954,  0.7880],
        [-1.6386,  1.9103,  0.7267],
        [ 1.0415,  0.1941,  0.6415],
        [-0.4898, -1.1911,  0.5955],
        [-0.3925,  1.2494, -1.0075],
        [ 1.4568,  0.7609, -0.2290],
        [ 1.2358, -0.2441,  0.2693],
        [-0.6857,  1.2298, -0.9312]], requires_grad=True)
torch.Size([10, 3])


In [3]:
inputs = torch.tensor([0,3,5])
print(inputs)
outputs = a(inputs)
print(outputs)

tensor([0, 3, 5])
tensor([[-0.7618, -0.2621, -0.8623],
        [-1.6386,  1.9103,  0.7267],
        [-0.4898, -1.1911,  0.5955]], grad_fn=<EmbeddingBackward0>)


In [ ]:
import torch 
import torch.nn as nn

class PositionalEncoding(nn.Module):
    '''
    PositionalEncoding 类用于给输入序列添加位置编码。
    位置编码确定输入序列中元素的位置信息，
    具体实现基于三角函数，为不同位置和维度生成不同的编码值。
    '''
    def __init__(self, n,d):
        super().__init__()
        # 初始化位置编码矩阵，第一维用于批次处理
        self.p = torch.zeros((1,n,d))
        # 生成从0到n-1的位置索引，形状为 (n, 1)
        i = torch.arange(n,dtype=torch.float32).reshape((-1,1))
        # 生成维度索引，步长为2，
        j = torch.arange(0,d,2,dtype=torch.float32)/d
        
        X = i/torch.pow(10000,j)
        self.p[:,:,0::2] = torch.sin(X)
        self.p[:,:,1::2] = torch.cos(X)
    def forward(self,X):
        return X+self.p

In [6]:
import torch 
import torch.nn as nn

dropout = nn.Dropout(0.1)
imputs = torch.randn(10000, dtype=torch.float32)
outputs = dropout(imputs)
print((outputs==0).sum().item())

1050
