In [1]:
import torch 
import torch.nn as nn
a = nn.Embedding(10, 3)
print(a.weight)
print(a.weight.shape)

Parameter containing:
tensor([[-0.7618, -0.2621, -0.8623],
        [ 0.4043, -1.4023,  1.1573],
        [-0.2983,  0.3954,  0.7880],
        [-1.6386,  1.9103,  0.7267],
        [ 1.0415,  0.1941,  0.6415],
        [-0.4898, -1.1911,  0.5955],
        [-0.3925,  1.2494, -1.0075],
        [ 1.4568,  0.7609, -0.2290],
        [ 1.2358, -0.2441,  0.2693],
        [-0.6857,  1.2298, -0.9312]], requires_grad=True)
torch.Size([10, 3])


In [3]:
inputs = torch.tensor([0,3,5])
print(inputs)
outputs = a(inputs)
print(outputs)

tensor([0, 3, 5])
tensor([[-0.7618, -0.2621, -0.8623],
        [-1.6386,  1.9103,  0.7267],
        [-0.4898, -1.1911,  0.5955]], grad_fn=<EmbeddingBackward0>)
