In [ ]:
# 数据加载处理
from torchvision.transforms import ToTensor
from torchvision.datasets import FashionMNIST

train_data = FashionMNIST(root='./data', train=True, download=True, transform=ToTensor())
test_data = FashionMNIST(root='./data', train=False, download=True, transform=ToTensor())
train_data[1000]


1.数据预处理
2.构建模型
3.定制模型损失函数和优化器
4.训练并观察超参数

In [27]:
import torch
import torch.nn as nn

# x输入(60000,784)
# 隐藏层(784,64) 参数矩阵
# 隐藏层(64) 偏置
# 输出层参数矩阵(64,10)
# 输出层偏置(10,)
# y结果(60000,10)
linear = nn.Linear(in_features=784, out_features=64, bias=True)
out = linear(torch.randn(5,784))
act = nn.Sigmoid()
out1 = act(out)

linear2 = nn.Linear(in_features=64, out_features=10, bias=True)
print(out1.shape)
out3 = linear2(out1)
print(out3)
final = nn.Softmax(dim=1)
out4 = final(out3)
print(out4)


torch.Size([5, 64])
tensor([[ 0.1406, -0.0086,  0.0047,  0.5930, -0.1242, -0.1971, -0.1275, -0.1839,
          0.4931,  0.5259],
        [ 0.2453, -0.0844,  0.1671,  0.5047, -0.1551, -0.1343, -0.0358, -0.3185,
          0.3625,  0.2968],
        [ 0.2368, -0.0185,  0.0830,  0.6275, -0.0526, -0.1607, -0.1085, -0.3026,
          0.4020,  0.4678],
        [ 0.2135,  0.0905, -0.1385,  0.6620, -0.2132, -0.0904, -0.2322, -0.2047,
          0.6250,  0.5907],
        [ 0.0706, -0.0469, -0.0186,  0.5980, -0.1463, -0.2838, -0.1256, -0.3653,
          0.3999,  0.5538]], grad_fn=<AddmmBackward0>)
tensor([[0.0984, 0.0847, 0.0858, 0.1546, 0.0755, 0.0702, 0.0752, 0.0711, 0.1399,
         0.1446],
        [0.1137, 0.0818, 0.1051, 0.1474, 0.0762, 0.0778, 0.0858, 0.0647, 0.1278,
         0.1197],
        [0.1080, 0.0837, 0.0926, 0.1596, 0.0808, 0.0726, 0.0764, 0.0630, 0.1274,
         0.1360],
        [0.1019, 0.0901, 0.0717, 0.1596, 0.0665, 0.0752, 0.0653, 0.0671, 0.1538,
         0.1486],
        [0.0

In [30]:
# 所有的结构串联
model = nn.Sequential(
    nn.Linear(28*28, 256),
    nn.Sigmoid(),
    nn.Linear(256, 10)
)
model

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=256, out_features=10, bias=True)
)

In [32]:
# 损失函数
loss_fn = nn.CrossEntropyLoss() # 交叉熵损失函数，多分类问题一般都是用交叉熵损失函数
print(loss_fn)
# 优化器 模型参数更新
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) # 随机梯度下降优化器，学习率为0.01
[param for param in model.parameters()]

CrossEntropyLoss()


[Parameter containing:
 tensor([[ 0.0167, -0.0294, -0.0254,  ..., -0.0247, -0.0297, -0.0018],
         [ 0.0109,  0.0079, -0.0167,  ...,  0.0229, -0.0060,  0.0067],
         [ 0.0196,  0.0124, -0.0349,  ...,  0.0352,  0.0124,  0.0115],
         ...,
         [-0.0197,  0.0273,  0.0195,  ...,  0.0059, -0.0136,  0.0346],
         [ 0.0280, -0.0330, -0.0143,  ..., -0.0223,  0.0242,  0.0010],
         [ 0.0031, -0.0142,  0.0346,  ..., -0.0157,  0.0017,  0.0153]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0318,  0.0021,  0.0082, -0.0189,  0.0306,  0.0338, -0.0257,  0.0001,
          0.0244,  0.0089,  0.0050,  0.0245,  0.0062, -0.0044, -0.0331, -0.0313,
         -0.0170,  0.0333,  0.0346, -0.0055,  0.0210,  0.0031,  0.0064,  0.0241,
          0.0201,  0.0242,  0.0030, -0.0259,  0.0210,  0.0092,  0.0176, -0.0227,
         -0.0185, -0.0035, -0.0301,  0.0270, -0.0313, -0.0192,  0.0052,  0.0094,
         -0.0258,  0.0008,  0.0171, -0.0176, -0.0252, -0.0185,  0.0301, -0.0304

# pytorch fashionmnist数据集 神经网络搭建和训练

In [103]:
# 导入必要包
import torch
import torch.nn as nn
from torchvision.transforms.v2 import ToTensor # 转换图像数据为张量
from torchvision.datasets import FashionMNIST
from torch.utils.data import DataLoader # 数据加载器

In [134]:
# 定义超参数
LR = 0.01
epochs = 20
BATCH_SIZE = 128

In [135]:
# 数据集加载
train_data = FashionMNIST(root='./data', train=True, download=True, transform=ToTensor())
test_data = FashionMNIST(root='./data', train=False, download=True, transform=ToTensor())
# print(train_data[0])
# print(type(train_data[0][0]))
# print(type(train_data[0][1]))

c:\Users\xiong\.conda\envs\py312\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(


In [136]:
train_dl = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)

In [137]:
# 模型定义
model = nn.Sequential(
    nn.Linear(784, 128),
    nn.Sigmoid(),
    nn.Linear(128, 64),
    nn.Sigmoid(),
    nn.Linear(64, 10)
)

In [138]:
# 损失函数和优化器
loss_fn = nn.CrossEntropyLoss()  # 交叉熵损失函数
optimizer = torch.optim.SGD(model.parameters(), lr=LR)  # 随机梯度下降优化器
# count = 0
# for param in model.parameters():
#     print(param)
#     count += 1
# print(count)

In [121]:
print(type(train_dl))
for a in train_dl:
    print(a[1])
    break

<class 'torch.utils.data.dataloader.DataLoader'>
tensor([7, 5, 4, 9, 0, 7, 5, 8, 5, 4, 2, 4, 8, 6, 7, 9, 4, 1, 0, 8, 5, 0, 1, 4,
        7, 6, 9, 6, 9, 1, 7, 1, 1, 6, 4, 9, 5, 4, 9, 1, 0, 2, 2, 4, 6, 6, 3, 4,
        2, 1, 6, 2, 4, 8, 8, 4, 4, 0, 2, 6, 1, 6, 3, 7, 4, 6, 1, 4, 7, 2, 4, 5,
        5, 5, 0, 7, 6, 4, 2, 2, 7, 8, 6, 3, 5, 5, 4, 2, 8, 2, 6, 0, 5, 4, 4, 6,
        0, 8, 6, 8, 1, 7, 7, 9, 8, 7, 0, 0, 1, 5, 9, 6, 0, 2, 8, 2, 3, 7, 8, 4,
        3, 0, 8, 3, 6, 7, 9, 7])


In [139]:
for epoch in range(epochs):    
    for data, target in train_dl:
        # 前向运算
        output = model(data.reshape(-1, 784))
        # 计算损失
        loss = loss_fn(output, target)
        # 反向传播
        optimizer.zero_grad() # 所有参数梯度清零
        loss.backward()
        optimizer.step() # 更新参数 
    print(f'Epoch:{epoch} Loss: {loss.item()}')
    

Epoch:0 Loss: 2.298168897628784
Epoch:1 Loss: 2.2941811084747314
Epoch:2 Loss: 2.2828450202941895
Epoch:3 Loss: 2.272071361541748
Epoch:4 Loss: 2.2442948818206787
Epoch:5 Loss: 2.1958401203155518
Epoch:6 Loss: 2.12853741645813
Epoch:7 Loss: 1.9328991174697876
Epoch:8 Loss: 1.7977286577224731
Epoch:9 Loss: 1.6834653615951538
Epoch:10 Loss: 1.6045740842819214
Epoch:11 Loss: 1.4776787757873535
Epoch:12 Loss: 1.390397071838379
Epoch:13 Loss: 1.2965580224990845
Epoch:14 Loss: 1.1460697650909424
Epoch:15 Loss: 1.216450810432434
Epoch:16 Loss: 1.1548116207122803
Epoch:17 Loss: 1.0856159925460815
Epoch:18 Loss: 1.1114213466644287
Epoch:19 Loss: 1.0018080472946167


In [140]:
# 测试
test_dl = DataLoader(test_data, batch_size=BATCH_SIZE)
current = 0
total = 0
with torch.no_grad():
    for data, target in test_dl:
        output = model(data.reshape(-1, 28*28))
        _, predicted = torch.max(output, 1)
        total += target.size(0)
        current += (predicted == target).sum().item()
print('Accuracy: %d %%' % (100 * current / total))

Accuracy: 61 %
